
import React from 'react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Brain } from 'lucide-react';

interface AISummaryProps {
  summary: string;
  userType?: string;
}

const AISummary: React.FC<AISummaryProps> = ({ summary, userType }) => {
  const formatSummary = (text: string) => {
    // Simple markdown-like formatting
    return text
      .split('\n')
      .map((line, index) => {
        if (line.startsWith('**') && line.endsWith('**')) {
          return <h4 key={index} className="font-bold mt-4 mb-2">{line.slice(2, -2)}</h4>;
        }
        if (line.startsWith('### ')) {
          return <h4 key={index} className="font-bold mt-4 mb-2">{line.slice(4)}</h4>;
        }
        if (line.startsWith('- ')) {
          return <li key={index} className="ml-4 mb-1">{line.slice(2)}</li>;
        }
        if (line.trim() === '') {
          return <br key={index} />;
        }
        return <p key={index} className="mb-2">{line}</p>;
      });
  };

  return (
    <Card className="p-6">
      <div className="flex items-center gap-2 mb-4">
        <Brain className="w-6 h-6 text-purple-600" />
        <h3 className="text-xl font-bold">AI-Powered Analysis</h3>
        {userType && (
          <Badge variant="outline" className="ml-auto">
            Optimized for {userType}
          </Badge>
        )}
      </div>
      
      <div className="prose prose-sm max-w-none">
        {formatSummary(summary)}
      </div>
      
      <div className="mt-4 p-3 bg-muted rounded-lg text-xs text-muted-foreground">
        <p>💡 This analysis is generated by AI and should be used as a guide. Always verify specifications and prices before making a purchase.</p>
      </div>
    </Card>
  );
};

export default AISummary;
